source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
gem "jekyll", ">= 3.9.0"
# gem 'jekyll-feed'
# gem 'jemoji'
gem 'webrick'
gem 'wdm', '>= 0.1.0'
gem "jekyll-remote-theme"
gem "jekyll-sitemap"
gem "github-pages", group: :jekyll_plugins
